Updates

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -4,10 +4,10 @@ name: Rust Checks
 on:
   push:
     branches: [ main ]
-    # paths: [ .github/workflows/checks.yml, keys/**, src/**, test/**, build.rs, Cargo.lock, Cargo.toml, Cross.toml, rustfmt.toml ]
+    paths: [ .github/workflows/checks.yml, keys/**, src/**, test/**, build.rs, Cargo.lock, Cargo.toml, Cross.toml, deny.toml, rustfmt.toml ]
   pull_request:
     branches: [ main ]
-    # paths: [ .github/workflows/checks.yml, keys/**, src/**, test/**, build.rs, Cargo.lock, Cargo.toml, Cross.toml, rustfmt.toml ]
+    paths: [ .github/workflows/checks.yml, keys/**, src/**, test/**, build.rs, Cargo.lock, Cargo.toml, Cross.toml, deny.toml, rustfmt.toml ]
   workflow_dispatch:
 
 env:
@@ -50,7 +50,7 @@ jobs:
           pkgs: cargo-audit
       - uses: Swatinem/rust-cache@v2
       - name: Cache Advisory DB
-        uses: actions/cache@v3
+        uses: actions/cache@v4
         with:
           path: |
             ~/.cargo/advisory-db
@@ -77,8 +77,8 @@ jobs:
         include:
           - target: x86_64-unknown-linux-gnu
             os: ubuntu-latest
-          - target: x86_64-apple-darwin
-            os: macos-latest
+          - target: aarch64-apple-darwin
+            os: macos-14
           - target: x86_64-pc-windows-msvc
             os: windows-latest
     runs-on: ${{ matrix.os }}
@@ -89,6 +89,8 @@ jobs:
           rustup update
           rustc --version
       - uses: Swatinem/rust-cache@v2
+        with:
+          key: ${{ matrix.target }}
       - name: Clippy Check
         shell: bash
         run: |
@@ -115,8 +117,8 @@ jobs:
         include:
           - target: x86_64-unknown-linux-gnu
             os: ubuntu-latest
-          - target: x86_64-apple-darwin
-            os: macos-latest
+          - target: aarch64-apple-darwin
+            os: macos-14
           - target: x86_64-pc-windows-msvc
             os: windows-latest
     runs-on: ${{ matrix.os }}
@@ -130,6 +132,8 @@ jobs:
         with:
           pkgs: cargo-hack
       - uses: Swatinem/rust-cache@v2
+        with:
+          key: ${{ matrix.target }}
       - name: Hack Check (each-feature)
         shell: bash
         run: |
@@ -140,6 +144,35 @@ jobs:
         run: |
           set -o pipefail
           cargo hack check --feature-powerset ${{ env.hack-group }} --no-dev-deps --verbose --workspace --locked 2>&1 | tee .step-data.txt
+      - name: Put into summary (success)
+        if: success()
+        shell: bash
+        run: echo "Success" >> $GITHUB_STEP_SUMMARY
+      - name: Put into summary (failure)
+        if: failure()
+        shell: bash
+        run: |
+          echo "Failed!" >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`shell" >> $GITHUB_STEP_SUMMARY
+          cat .step-data.txt >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+
+  cargo-deny:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Update Rust
+        run: |
+          rustup update
+          rustc --version
+      - uses: cargo-prebuilt/cargo-prebuilt-action@v3
+        with:
+          pkgs: cargo-deny
+      - name: Cargo Deny
+        shell: bash
+        run: |
+          set -o pipefail
+          cargo deny check 2>&1 | tee .step-data.txt
       - name: Put into summary (success)
         if: success()
         shell: bash
diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -29,29 +29,31 @@ jobs:
           text: ${{ github.ref }}
           regex: '^refs\/tags\/v\d+\.\d+\.\d+$'
 
-  # publish-crates-io:
-  #   runs-on: ubuntu-latest
-  #   needs: [ release, check-fmt, clippy, cross, apple-darwin, pc-windows-msvc ]
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #     - name: Update Rust
-  #       run: |
-  #         rustup update
-  #         rustc --version
-  #     - name: Publish
-  #       run: cargo publish --verbose --locked --token ${CRATES_TOKEN}
-  #       env:
-  #         CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
+#  publish-crates-io:
+#    if: ${{ ! contains(github.ref, '-dev') }}
+#    runs-on: ubuntu-latest
+#    needs: [ release, check-fmt, clippy, ink-cross, cross, apple-darwin, pc-windows-msvc ]
+#    steps:
+#      - uses: actions/checkout@v4
+#      - name: Update Rust
+#        run: |
+#          rustup update
+#          rustc --version
+#      - name: Publish
+#        run: cargo publish --verbose --locked --token ${CRATES_TOKEN}
+#        env:
+#          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
 
   publish-github-releases:
     runs-on: ubuntu-latest
-    needs: [ release, check-fmt, clippy, cross, apple-darwin, pc-windows-msvc ]
+    needs: [ release, check-fmt, clippy, ink-cross, cross, apple-darwin, pc-windows-msvc ]
     steps:
       - uses: actions/checkout@v4
-      - uses: actions/download-artifact@v3
+      - uses: actions/download-artifact@v4
       - name: Merge hashes
         shell: bash
         run: |
+          set -euxo pipefail
           echo -n "" > hashes.sha256
           for D in target-*; do
             if [ -d "${D}" ]; then
@@ -61,30 +63,31 @@ jobs:
               popd
             fi
           done
-      # - name: Sign archives
-      #   shell: bash
-      #   run: |
-      #     eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
-      #     brew install minisign
-      #     echo -n "$SIGNING_KEY" | base64 --decode > ~/.minisign_secret.key
-      #     for D in target-*; do
-      #       if [ -d "${D}" ]; then
-      #         echo "${D}"
-      #         pushd "${D}"
-        
-      #         for file in ./*.tar.gz ./*.zip; do
-      #           if [ -f "$file" ]; then
-      #             minisign -S -s ~/.minisign_secret.key -m $file
-      #             minisign -V -p ../keys/cargo-prebuilt.pub -m $file
-      #           fi 
-      #         done
-                
-      #         popd
-      #       fi
-      #     done
-      #     rm -f ~/.minisign_secret.key
-      #   env:
-      #     SIGNING_KEY: ${{ secrets.MINISIGN_SIGNING_KEY }}
+#      - name: Sign archives
+#        shell: bash
+#        run: |
+#          set -euxo pipefail
+#          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
+#          brew install minisign
+#          echo -n "$SIGNING_KEY" | base64 --decode > ~/.minisign_secret.key
+#          for D in target-*; do
+#            if [ -d "${D}" ]; then
+#              echo "${D}"
+#              pushd "${D}"
+#
+#              for file in ./*.tar.gz ./*.zip; do
+#                if [ -f "$file" ]; then
+#                  minisign -S -s ~/.minisign_secret.key -m $file
+#                  minisign -V -p ../keys/cargo-prebuilt.pub -m $file
+#                fi
+#              done
+#
+#              popd
+#            fi
+#          done
+#          rm -f ~/.minisign_secret.key
+#        env:
+#          SIGNING_KEY: ${{ secrets.MINISIGN_SIGNING_KEY }}
       - name: Create and push artifacts to release
         uses: ncipollo/release-action@v1
         with:
@@ -125,8 +128,8 @@ jobs:
         include:
           - target: x86_64-unknown-linux-gnu
             os: ubuntu-latest
-          - target: x86_64-apple-darwin
-            os: macos-latest
+          - target: aarch64-apple-darwin
+            os: macos-14
           - target: x86_64-pc-windows-msvc
             os: windows-latest
     env:
@@ -166,8 +169,8 @@ jobs:
         include:
           - target: x86_64-unknown-linux-gnu
             os: ubuntu-latest
-          - target: x86_64-apple-darwin
-            os: macos-latest
+          - target: aarch64-apple-darwin
+            os: macos-14
           - target: x86_64-pc-windows-msvc
             os: windows-latest
     env:
@@ -214,8 +217,8 @@ jobs:
         include:
           - target: x86_64-unknown-linux-gnu
             os: ubuntu-latest
-          - target: x86_64-apple-darwin
-            os: macos-latest
+          - target: aarch64-apple-darwin
+            os: macos-14
           - target: x86_64-pc-windows-msvc
             os: windows-latest
     env:
@@ -252,6 +255,37 @@ jobs:
           cat .step-data.txt >> $GITHUB_STEP_SUMMARY
           echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
 
+  cargo-deny:
+    env:
+      CARGO_TERM_COLOR: never
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Update Rust
+        run: |
+          rustup update
+          rustc --version
+      - uses: cargo-prebuilt/cargo-prebuilt-action@v3
+        with:
+          pkgs: cargo-deny
+      - name: Cargo Deny
+        shell: bash
+        run: |
+          set -o pipefail
+          cargo deny check 2>&1 | tee .step-data.txt
+      - name: Put into summary (success)
+        if: success()
+        shell: bash
+        run: echo "Success" >> $GITHUB_STEP_SUMMARY
+      - name: Put into summary (failure)
+        if: failure()
+        shell: bash
+        run: |
+          echo "Failed!" >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`shell" >> $GITHUB_STEP_SUMMARY
+          cat .step-data.txt >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+
   reports:
     runs-on: ubuntu-latest
     steps:
@@ -266,7 +300,7 @@ jobs:
       - uses: Swatinem/rust-cache@v2
         if: ${{ env.cache == 'true' }}
       - name: Cache Advisory DB
-        uses: actions/cache@v3
+        uses: actions/cache@v4
         with:
           path: |
             ~/.cargo/advisory-db
@@ -287,44 +321,82 @@ jobs:
           cargo audit >> $GITHUB_STEP_SUMMARY || true
           echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
 
+  ink-cross:
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+          - target: aarch64-unknown-linux-gnu
+            can-test: false
+          - target: aarch64-unknown-linux-musl
+            can-test: false
+          - target: armv7-unknown-linux-gnueabihf
+            can-test: false
+          - target: armv7-unknown-linux-musleabihf
+            can-test: false
+          - target: powerpc64le-unknown-linux-gnu
+            can-test: false
+          - target: riscv64gc-unknown-linux-gnu
+            can-test: false
+          - target: s390x-unknown-linux-gnu
+            can-test: false
+          - target: x86_64-unknown-linux-gnu
+            can-test: true
+          - target: x86_64-unknown-linux-musl
+            can-test: true
+    runs-on: ubuntu-latest
+    needs: [ check-fmt, clippy, cargo-hack, cargo-msrv, cargo-deny ]
+    steps:
+      - uses: actions/checkout@v4
+      - uses: cargo-prebuilt/cargo-prebuilt-action@v3
+        with:
+          pkgs: coreutils
+      - uses: Swatinem/rust-cache@v2
+        if: ${{ env.cache == 'true' }}
+      - name: Run tests
+        if: ${{ matrix.can-test }}
+        run: |
+          docker run --rm \
+          --userns host --user $(id -u):$(id -g) \
+          -v $HOME/.cargo/registry:/usr/local/cargo/registry \
+          -v ./:/project \
+          ghcr.io/cargo-prebuilt/ink-cross:stable-${{ matrix.target }} \
+          test --verbose --workspace --release --locked --target ${{ matrix.target }} ${{ env.feature-set }}
+      - name: Build
+        run: |
+          docker run --rm \
+          --userns host --user $(id -u):$(id -g) \
+          -v $HOME/.cargo/registry:/usr/local/cargo/registry \
+          -v ./:/project \
+          ghcr.io/cargo-prebuilt/ink-cross:stable-${{ matrix.target }} \
+          auditable build --verbose --workspace --release --locked --target ${{ matrix.target }} ${{ env.feature-set }}
+      - name: Tar
+        run: tar czvf ${{ matrix.target }}.tar.gz -C ./target/${{ matrix.target }}/release ${{ env.bin-name }}
+      - name: Hash
+        run: echo "$(coreutils sha256sum ${{ matrix.target }}.tar.gz)" > ${{ matrix.target }}.sha256
+      - name: Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: target-${{ matrix.target }}
+          path: |
+            ${{ matrix.target }}.tar.gz
+            ${{ matrix.target }}.sha256
+
   cross:
     strategy:
       fail-fast: false
       matrix:
         include:
-          - target: x86_64-unknown-linux-gnu
-            can-test: true
-          - target: x86_64-unknown-linux-musl
-            can-test: true
-          - target: aarch64-unknown-linux-gnu
-            can-test: true
-          - target: aarch64-unknown-linux-musl
-            can-test: true
           - target: x86_64-unknown-freebsd
             can-test: false
           - target: x86_64-unknown-netbsd
             can-test: false
           - target: x86_64-unknown-illumos
             can-test: false
-          - target: x86_64-sun-solaris
-            can-test: false
-          - target: riscv64gc-unknown-linux-gnu
-            can-test: true
           - target: powerpc64-unknown-linux-gnu
             can-test: true
-          - target: powerpc64le-unknown-linux-gnu
-            can-test: true
-          - target: s390x-unknown-linux-gnu
-            can-test: true
-          - target: armv7-unknown-linux-gnueabihf
-            can-test: true
-          - target: armv7-unknown-linux-musleabihf
-            can-test: true
-          - target: x86_64-pc-windows-gnu
-            can-test: true
-            ending: .exe
     runs-on: ubuntu-latest
-    needs: [ check-fmt, clippy, cargo-hack, cargo-msrv ]
+    needs: [ check-fmt, clippy, cargo-hack, cargo-msrv, cargo-deny ]
     steps:
       - uses: actions/checkout@v4
       - name: Update Rust and add target
@@ -343,11 +415,11 @@ jobs:
       - name: Build
         run: cross build --verbose --workspace --release --locked --target ${{ matrix.target }} ${{ env.feature-set }}
       - name: Tar
-        run: tar czvf ${{ matrix.target }}.tar.gz -C ./target/${{ matrix.target }}/release ${{ env.bin-name }}${{ matrix.ending }}
+        run: tar czvf ${{ matrix.target }}.tar.gz -C ./target/${{ matrix.target }}/release ${{ env.bin-name }}
       - name: Hash
         run: echo "$(coreutils sha256sum ${{ matrix.target }}.tar.gz)" > ${{ matrix.target }}.sha256
       - name: Artifact
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         with:
           name: target-${{ matrix.target }}
           path: |
@@ -360,11 +432,11 @@ jobs:
       matrix:
         include:
           - target: x86_64-apple-darwin
-            can-test: true
+            os: macos-13
           - target: aarch64-apple-darwin
-            can-test: false
-    runs-on: macos-latest
-    needs: [ check-fmt, clippy, cargo-hack, cargo-msrv ]
+            os: macos-14
+    runs-on: ${{ matrix.os }}
+    needs: [ check-fmt, clippy, cargo-hack, cargo-msrv, cargo-deny ]
     steps:
       - uses: actions/checkout@v4
       - name: Update Rust and add target
@@ -378,7 +450,6 @@ jobs:
       - uses: Swatinem/rust-cache@v2
         if: ${{ env.cache == 'true' }}
       - name: Run tests
-        if: ${{ matrix.can-test }}
         run: cargo test --verbose --workspace --release --locked --target ${{ matrix.target }} ${{ env.feature-set }}
       - name: Build
         run: cargo auditable build --verbose --workspace --release --locked --target ${{ matrix.target }} ${{ env.feature-set }}
@@ -387,7 +458,7 @@ jobs:
       - name: Hash
         run: echo "$(coreutils sha256sum ${{ matrix.target }}.tar.gz)" > ${{ matrix.target }}.sha256
       - name: Artifact
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         with:
           name: target-${{ matrix.target }}
           path: |
@@ -404,7 +475,7 @@ jobs:
           - target: aarch64-pc-windows-msvc
             can-test: false
     runs-on: windows-latest
-    needs: [ check-fmt, clippy, cargo-hack, cargo-msrv ]
+    needs: [ check-fmt, clippy, cargo-hack, cargo-msrv, cargo-deny ]
     steps:
       - uses: actions/checkout@v4
       - name: Update Rust and add target
@@ -423,14 +494,13 @@ jobs:
       - name: Build
         run: cargo auditable build --verbose --workspace --release --locked --target ${{ matrix.target }} ${{ env.feature-set }}
       - name: Zip
-        uses: vimtor/action-zip@v1.1
-        with:
-          files: ./target/${{ matrix.target }}/release/${{ env.bin-name }}.exe
-          dest: ${{ matrix.target }}.zip
+        run: |
+          cd target/${{ matrix.target }}/release
+          7z a -tzip ../../../${{ matrix.target }}.zip ${{ env.bin-name }}.exe
       - name: Hash
         run: echo "$(coreutils sha256sum ${{ matrix.target }}.zip)" > ${{ matrix.target }}.sha256
       - name: Artifact
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         with:
           name: target-${{ matrix.target }}
           path: |
