Cargo-msrv

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -1,7 +1,7 @@
 name: Rust Checks
 ### Name: Rust Checks
 ### Author: harmless-tech
-### Version: audit-2.0.0
+### Version: audit-3.0.0
 ### Git Repo: https://github.com/harmless-tech/rust-github-actions
 
 on:
@@ -120,6 +120,45 @@ jobs:
         run: |
           set -o pipefail
           cargo hack check --feature-powerset --no-dev-deps --verbose --workspace --locked 2>&1 | tee .step-data.txt
+      - name: Put into summary (success)
+        if: success()
+        shell: bash
+        run: echo "Success" >> $GITHUB_STEP_SUMMARY
+      - name: Put into summary (failure)
+        if: failure()
+        shell: bash
+        run: |
+          echo "Failed!" >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`shell" >> $GITHUB_STEP_SUMMARY
+          cat .step-data.txt >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+
+  cargo-msrv:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/cache@v3
+        with:
+          path: |
+            ~/.cargo/registry/index
+            ~/.cargo/registry/cache
+            ~/.cargo/git/db
+            target
+          key: ${{ runner.os }}-cargo-msrv-${{ hashFiles('**/Cargo.lock') }}
+      - name: Update Rust
+        run: rustup update
+      - name: Rust Version
+        run: rustc --version
+      - uses: cargo-prebuilt/cargo-prebuilt-action@v1
+        with:
+          tools: cargo-binstall
+      - name: Install cargo-msrv
+        run: cargo binstall --version 0.16.0-beta.11 --no-confirm cargo-msrv
+      - name: MSRV Check
+        shell: bash
+        run: |
+          set -o pipefail
+          cargo msrv --verbose --workspace --locked 2>&1 | tee .step-data.txt
       - name: Put into summary (success)
         if: success()
         shell: bash
