Combine clippy

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,7 +1,7 @@
 name: Rust Build, Test, and Release
 ## Name: Rust Build, Test, and Release
 ## Author: harmless-tech
-## Version: cache-based-1.2.3
+## Version: audit-1.0.0
 ## Git Repo: https://github.com/harmless-tech/rust-github-actions
 
 on:
@@ -39,86 +39,24 @@ jobs:
           cat .step-data.txt >> $GITHUB_STEP_SUMMARY
           echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
 
-  clippy-x86_64-unknown-linux-gnu:
+  clippy:
+    strategy:
+      fail-fast: false
+      matrix:
+        target:
+          - target: x86_64-unknown-linux-gnu
+            os: ubuntu-latest
+          - target: x86_64-apple-darwin
+            os: macos-latest
+          - target: x86_64-pc-windows-msvc
+            os: windows-latest
     env:
       CARGO_TERM_COLOR: never
-    runs-on: ubuntu-latest
-    needs: [ setup ]
-    steps:
-      - uses: actions/checkout@v3
-      - name: Get deps from cache
-        uses: actions/cache@v3
-        with:
-          path: |
-            .cargo-store
-          key: deps-cache-${{ hashFiles('**/Cargo.lock') }}
-          enableCrossOsArchive: true
-          fail-on-cache-miss: true
-      - name: Move deps
-        run: mv ./.cargo-store/* ~/.cargo
-      - name: Update Rust
-        run: rustup update
-      - name: Rust Version
-        run: rustc --version
-      - name: Clippy Check
-        run: |
-          set -o pipefail
-          cargo clippy --all-targets --all-features --verbose --workspace --release --locked -- -D warnings 2>&1 | tee .step-data.txt
-      - name: Put into summary (success)
-        if: success()
-        run: echo "Success" >> $GITHUB_STEP_SUMMARY
-      - name: Put into summary (failure)
-        if: failure()
-        run: |
-          echo "Failed!" >> $GITHUB_STEP_SUMMARY
-          echo "\`\`\`shell" >> $GITHUB_STEP_SUMMARY
-          cat .step-data.txt >> $GITHUB_STEP_SUMMARY
-          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
-          
-  clippy-x86_64-apple-darwin:
-    env:
-      CARGO_TERM_COLOR: never
-    runs-on: macos-latest
-    needs: [ setup ]
-    steps:
-      - uses: actions/checkout@v3
-      - name: Get deps from cache
-        uses: actions/cache@v3
-        with:
-          path: |
-            .cargo-store
-          key: deps-cache-${{ hashFiles('**/Cargo.lock') }}
-          enableCrossOsArchive: true
-          fail-on-cache-miss: true
-      - name: Move deps
-        run: mv ./.cargo-store/* ~/.cargo
-      - name: Update Rust
-        run: rustup update
-      - name: Rust Version
-        run: rustc --version
-      - name: Clippy Check
-        run: |
-          set -o pipefail
-          cargo clippy --all-targets --all-features --verbose --workspace --release --locked -- -D warnings 2>&1 | tee .step-data.txt
-      - name: Put into summary (success)
-        if: success()
-        run: echo "Success" >> $GITHUB_STEP_SUMMARY
-      - name: Put into summary (failure)
-        if: failure()
-        run: |
-          echo "Failed!" >> $GITHUB_STEP_SUMMARY
-          echo "\`\`\`shell" >> $GITHUB_STEP_SUMMARY
-          cat .step-data.txt >> $GITHUB_STEP_SUMMARY
-          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
-
-  clippy-x86_64-pc-windows-msvc:
-    env:
-      CARGO_TERM_COLOR: never
-    runs-on: windows-latest
-    needs: [ setup ]
+    runs-on: ${{ matrix.os }}
     steps:
       - uses: actions/checkout@v3
       - name: Change file endings in Cargo.lock
+        if: ${{ contains( matrix.os, 'windows' ) }}
         shell: pwsh
         run: (Get-Content -Raw Cargo.lock) -replace "`r`n","`n" | Set-Content Cargo.lock -NoNewline
       - name: Get deps from cache
@@ -136,17 +74,22 @@ jobs:
       - name: Rust Version
         run: rustc --version
       - name: Clippy Check
-        run: cargo clippy --all-targets --all-features --verbose --workspace --release --locked -- -D warnings 2>&1 | tee .step-data.txt
+        shell: bash
+        run: |
+          set -o pipefail
+          cargo clippy --all-targets --all-features --verbose --workspace --release --locked -- -D warnings 2>&1 | tee .step-data.txt
       - name: Put into summary (success)
         if: success()
-        run: echo "Success" >> $env:GITHUB_STEP_SUMMARY
+        shell: bash
+        run: echo "Success" >> $GITHUB_STEP_SUMMARY
       - name: Put into summary (failure)
         if: failure()
+        shell: bash
         run: |
-          echo "Failed!" >> $env:GITHUB_STEP_SUMMARY
-          "``````powershell" >> $env:GITHUB_STEP_SUMMARY
-          cat .step-data.txt >> $env:GITHUB_STEP_SUMMARY
-          "``````" >> $env:GITHUB_STEP_SUMMARY
+          echo "Failed!" >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`shell" >> $GITHUB_STEP_SUMMARY
+          cat .step-data.txt >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
 
   setup:
     runs-on: ubuntu-latest
@@ -215,7 +158,6 @@ jobs:
       name: ${{ github.ref_name }}
       prerelease: ${{ steps.regex-tag.outputs.match == '' }}
     runs-on: ubuntu-latest
-    needs: [ check-fmt, clippy-x86_64-unknown-linux-gnu, clippy-x86_64-apple-darwin, clippy-x86_64-pc-windows-msvc ]
     steps:
       - uses: actions/checkout@v3
       - uses: KyoriPowered/action-regex-match@v3
@@ -226,7 +168,7 @@ jobs:
 
   publish:
     runs-on: ubuntu-latest
-    needs: [ release, check-fmt, clippy-x86_64-unknown-linux-gnu, clippy-x86_64-apple-darwin, clippy-x86_64-pc-windows-msvc, x86_64-unknown-linux-gnu, apple-darwin, pc-windows-msvc, cross ]
+    needs: [ release, check-fmt, clippy x86_64-unknown-linux-gnu, apple-darwin, pc-windows-msvc, cross ]
     steps:
       - uses: actions/checkout@v3
       - name: Get deps from cache
