Add release

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -150,6 +150,67 @@ jobs:
           cat .step-data.txt >> $GITHUB_STEP_SUMMARY
           echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
 
+  cargo-hack:
+    strategy:
+      fail-fast: true
+      matrix:
+        include:
+          - target: x86_64-unknown-linux-gnu
+            os: ubuntu-latest
+          - target: x86_64-apple-darwin
+            os: macos-latest
+          - target: x86_64-pc-windows-msvc
+            os: windows-latest
+    env:
+      CARGO_TERM_COLOR: never
+    runs-on: ${{ matrix.os }}
+    needs: [ setup ]
+    steps:
+      - uses: actions/checkout@v3
+      - name: Change file endings in Cargo.lock
+        if: ${{ contains( matrix.os, 'windows' ) }}
+        shell: pwsh
+        run: (Get-Content -Raw Cargo.lock) -replace "`r`n","`n" | Set-Content Cargo.lock -NoNewline
+      - name: Get deps from cache
+        uses: actions/cache@v3
+        with:
+          path: |
+            .cargo-store
+          key: deps-cache-${{ hashFiles('**/Cargo.lock') }}
+          enableCrossOsArchive: true
+          fail-on-cache-miss: true
+      - name: Move deps
+        run: mv ./.cargo-store/* ~/.cargo
+      - name: Update Rust
+        run: rustup update
+      - name: Rust Version
+        run: rustc --version
+      - uses: cargo-prebuilt/cargo-prebuilt-action@v1
+        with:
+          tools: cargo-hack
+      - name: Hack Check (each-feature)
+        shell: bash
+        run: |
+          set -o pipefail
+          cargo hack check --each-feature --no-dev-deps --verbose --workspace --release --locked 2>&1 | tee .step-data.txt
+      - name: Hack Check (feature-powerset)
+        shell: bash
+        run: |
+          set -o pipefail
+          cargo hack check --feature-powerset --no-dev-deps --verbose --workspace --release --locked 2>&1 | tee .step-data.txt
+      - name: Put into summary (success)
+        if: success()
+        shell: bash
+        run: echo "Success" >> $GITHUB_STEP_SUMMARY
+      - name: Put into summary (failure)
+        if: failure()
+        shell: bash
+        run: |
+          echo "Failed!" >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`shell" >> $GITHUB_STEP_SUMMARY
+          cat .step-data.txt >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+
   setup:
     runs-on: ubuntu-latest
     steps:
@@ -293,7 +354,7 @@ jobs:
             can-test: true
             ending: .exe
     runs-on: ubuntu-latest
-    needs: [ release, setup, check-fmt, clippy ]
+    needs: [ release, setup, check-fmt, clippy, cargo-hack ]
     steps:
       - uses: actions/checkout@v3
       - name: Get deps from cache
@@ -343,7 +404,7 @@ jobs:
           - target: aarch64-apple-darwin
             can-test: false
     runs-on: macos-latest
-    needs: [ release, setup, check-fmt, clippy ]
+    needs: [ release, setup, check-fmt, clippy, cargo-hack ]
     steps:
       - uses: actions/checkout@v3
       - name: Get deps from cache
@@ -394,7 +455,7 @@ jobs:
           - target: i686-pc-windows-msvc
             can-test: true
     runs-on: windows-latest
-    needs: [ release, setup, check-fmt, clippy ]
+    needs: [ release, setup, check-fmt, clippy, cargo-hack ]
     steps:
       - uses: actions/checkout@v3
       - name: Change file endings in Cargo.lock
